### ISSUE TITLE
[bug] Fix L2_Launch_models_nemotron_vl test

### ISSUE THREAD

**Issue by chtruong814** [NVIDIA-NeMo/Megatron-Bridge#3011]
### Problem

The Fix L2_Launch_models_nemotron_vl test is failing.
https://github.com/NVIDIA-NeMo/Megatron-Bridge/actions/runs/23672968577/job/68974936162

```
    File "/opt/Megatron-Bridge/examples/conversion/hf_megatron_roundtrip_multi_gpu.py", line 143, in main
      megatron_model = model_provider.provide_distributed_model(wrap_with_ddp=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/Megatron-Bridge/src/megatron/bridge/models/model_provider.py", line 202, in provide_distributed_model
      model = get_model(
              ^^^^^^^^^^
    File "/opt/Megatron-Bridge/src/megatron/bridge/models/model_provider.py", line 565, in get_model
      _model = pre_wrap_hook(model)
               ^^^^^^^^^^^^^^^^^^^^
    File "/opt/Megatron-Bridge/src/megatron/bridge/models/model_provider.py", line 284, in composed_hook
      model = hook(model)
              ^^^^^^^^^^^
    File "/opt/Megatron-Bridge/src/megatron/bridge/models/conversion/model_bridge.py", line 858, in load_weights_hf_to_megatron
      if task.megatron_module is None:
         ^^^^^^^^^^^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'megatron_module'
```

This seems to be failing after this commit was merged for adding Nemotron Super
https://github.com/NVIDIA-NeMo/Megatron-Bridge/pull/2912

It passes on the previous commit:
https://github.com/NVIDIA-NeMo/Megatron-Bridge/actions/runs/23670535347/job/68968891109

### Minimal repro

```shell
Run the L2_Launch_models_nemotron_vl test
```

### Expected behavior

The test should pass

### Affected area

area:model

### Regression?

Yes

### Logs

```shell

```

**Comment by yaoyu-33** [comment]
Fixed and merged in #3016

**Comment by pruprakash** [comment]
## QA RCCA Analysis
**Date:** 2026-04-22
**Analyst:** AI QA Agent (qa-rcca-coverage skill)
**Issue:** #3011 — Fix L2_Launch_models_nemotron_vl test

### 1. Fix Reference
**PR:** Fix merged (CI test failure fix)

### 2. Root Cause
PR #2912 (adding Nemotron Super) introduced a regression that broke the `nemotron_vl` test. The `load_weights_hf_to_megatron()` function was receiving a `NoneType` task object:
```
AttributeError: 'NoneType' object has no attribute 'megatron_module'
```

This occurred in `model_bridge.py:858` when checking `task.megatron_module is None`.

### 3. Classification
**Type:** CODE BUG (regression from #2912)

### 4. Trigger Config
- L2_Launch_models_nemotron_vl CI test
- HF to Megatron weight conversion for Nemotron VL

### 5. Functional Test Coverage
**Verdict:** COVERED (via CI)

The failing CI test `L2_Launch_models_nemotron_vl` itself serves as the regression test. When the fix was applied, the CI test passed, confirming the fix.

### 6. Test Results
CI test `L2_Launch_models_nemotron_vl` now passes after fix.

### 7. Gap Analysis
None — CI test coverage is sufficient for this regression.

### 8. Recommendations
None — the existing CI test provides adequate coverage.

---
*Auto-generated by qa-rcca-coverage skill — QA RCCA Analysis v2*
