### ISSUE TITLE
 HFDatasetConversationProvider.__init__() got an unexpected keyword argument 'sequence_length' for qwen3vl finetune

### ISSUE THREAD

**Issue by shifangx** [NVIDIA-NeMo/Megatron-Bridge#1510]
**Describe the bug**
There is an error for QWen3VL finetune.

**Steps/Code to reproduce bug**

```
# run test for finetune qwen3vl
uv run python -m torch.distributed.run --nproc_per_node=8 \
    examples/recipes/qwen_vl/finetune_qwen_vl.py \
    --pretrained-checkpoint ${MEGATRON_MODEL_PATH} \
    --recipe qwen3_vl_3b_active_30b_moe_finetune_config \
    --dataset-type hf \
    dataset.maker_name=make_cord_v2_dataset \
    train.global_batch_size=8 \
    train.train_iters=800 \
    checkpoint.save=${SAVE_DIR}/  \
    2>&1 | tee ${SAVE_DIR}/qwen3-vl-30b.log
```

**Expected behavior**
The error message is as following:
```
  File "/lustre/fs1/portfolios/coreai/projects/coreai_dlalgo_mcore/users/shifangx/1.workspace/3.Megatron-Bridge_qwen3_vl/Megatron-Bridge/src/megatron/bridge/recipes/qwen_vl/qwen3vl.py", line 131, in qwen3_vl_3b_active_30b_moe_finetune_config
    return _qwen3_vl_common(**combined_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/fs1/portfolios/coreai/projects/coreai_dlalgo_mcore/users/shifangx/1.workspace/3.Megatron-Bridge_qwen3_vl/Megatron-Bridge/src/megatron/bridge/recipes/qwen_vl/qwen3vl.py", line 245, in _qwen3_vl_common
    dataset_cfg = HFDatasetConversationProvider(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HFDatasetConversationProvider.__init__() got an unexpected keyword argument 'sequence_length'
```

**Comment by pruprakash** [comment]
## QA RCCA Analysis

**Classification:** CODE BUG

### 1. Summary
Qwen3-VL finetune failed with `TypeError: HFDatasetConversationProvider.__init__() got an unexpected keyword argument 'sequence_length'` due to a parameter name mismatch after a refactoring.

### 2. Root Cause
PR #1023 renamed the `sequence_length` parameter to `seq_length` in `HFDatasetConversationProvider.__init__()`, but the call site in `qwen3vl.py` was not updated. This caused a `TypeError` when trying to finetune Qwen3-VL models using the HF dataset type.

### 3. Fix Analysis
**PR:** #1511 (merged 2025-11-27)  
**Files Changed:** `src/megatron/bridge/recipes/qwen_vl/qwen3vl.py`

**Change:**
```diff
- sequence_length=seq_length,
+ seq_length=seq_length,
```

### 4. Impact Assessment
- **Severity:** High (blocks finetune workflow entirely)
- **Scope:** All Qwen3-VL finetune with HF dataset type
- **User Impact:** Cannot run Qwen3-VL finetuning with HuggingFace datasets

### 5. Detection Gap
The bug was a regression introduced by PR #1023. The refactoring changed the parameter name but missed updating one call site. At the time of the bug, unit tests for Qwen3-VL recipes did not exist.

### 6. Existing Test Coverage
Unit tests now exist in `tests/unit_tests/recipes/qwen_vl/test_qwen3_vl_recipes.py` (added in PR #1769, January 2026). The tests `test_qwen3_vl_sft_has_hf_dataset_provider` and `test_qwen3_vl_peft_has_hf_dataset_provider` actually instantiate `HFDatasetConversationProvider`, which would catch this type of parameter mismatch going forward.

### 7. Test Coverage Verdict
**COVERED BY SUBSEQUENT TEST ADDITIONS**

While no tests existed at the time of the bug, comprehensive unit tests were added later (PR #1769) that would prevent similar regressions in the future.

### 8. Recommendations
1. Ensure recipe unit tests are added concurrently with new recipe implementations
2. Consider adding static analysis or IDE tooling to catch renamed parameters across the codebase
